### ISSUE TITLE
Bot Analytics Instrumented Dashboard Authentication Error

### ISSUE THREAD

**Issue by debnathSD** [Azure/ibex-dashboard#369]
I have configured this dashboard with App Insight Id and Key but I am facing this error when I am testing the connection using Query Tester: 

- message:"The provided credentials have insufficient access to perform the requested operation"
- code:"InsufficientAccessError"

Also, there is no data in any of the dashboards. Any solution for this?

**Comment by morsh** [comment]
Hi @debnathSD ,
Have you granted that key read access on application insights?

**Comment by debnathSD** [comment]
Yes morsh, I have granted read access

**Comment by rahulrai-in** [comment]
getting the same error.

**Comment by morsh** [comment]
@debnathSD I just checked and this is correct.
Since we wanted to make the dashboard more secure, we stopped any credentials from being sent to the client. This is why Query Tester doesn't work now, but it is not important for the dashboard to work for now.

If the dashboard is empty it is probably because you are not sending relevant information to the dashboard.
For native application insights data being sent from a Service Application, you can use **Application Insights Web Application**
If you want to connect to see analytics information on a bot application, you'll have to [add a connector to your bot application](https://github.com/Azure/ibex-dashboard/#adding-application-insights-instrumentation-to-your-bot).

Would this solve your problem?

**Comment by rahulrai-in** [comment]
Yes. I was not getting the data because of wrongly applied keys. Thanks for help.

**Comment by debnathSD** [comment]
@morsh: I had some proxy issue only! Yes it is resolved now and thanks for the support! 😊

**Comment by morsh** [comment]
np @debnathSD - happy to help

**Comment by ghost** [comment]
Morning Morsh. I have the same issue as above. I deployed it to azure, added the app id and key but when i test it it throw's this error. When I go to the query designer directly to query app insights the app id and key works. Any advice?

**Comment by rahulrai-in** [comment]
> Morning Morsh. I have the same issue as above. I deployed it to azure, added the app id and key but when i test it it throw's this error. When I go to the query designer directly to query app insights the app id and key works. Any advice?

The last commit in this project was over 2 years ago. I think it is no longer maintained.
